# CPU + GPU 4090
Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          46 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   32
  On-line CPU(s) list:    0-31
Vendor ID:                GenuineIntel
  Model name:             13th Gen Intel(R) Core(TM) i9-13900K

Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0



# CPU + GPU 3090
Architecture:                          x86_64
CPU op-mode(s):                      32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                      39 bits physical, 48 bits virtual
CPU:                                24
On-line CPU(s) list:                0-23
Vendor ID:                            GenuineIntel
Model name:                          12th Gen Intel(R) Core(TM) i9-12900KF
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0



# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                         mkl  
brotlipy                  0.7.0           py38h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2023.7.22        py38h06a4308_0  
cffi                      1.15.1           py38h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
contourpy                 1.1.1                    pypi_0    pypi
cryptography              41.0.3           py38hdda0065_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.12.1                   pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.12.4                   pypi_0    pypi
fonttools                 4.50.0                   pypi_0    pypi
freetype                  2.12.1               h4a9f257_0  
fsspec                    2023.9.2                 pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
giflib                    5.2.1                h5eee18b_3  
gmp                       6.2.1                h295c915_3  
gnutls                    3.6.15               he1e5248_0  
huggingface-hub           0.18.0                   pypi_0    pypi
idna                      3.4              py38h06a4308_0  
importlib-resources       6.4.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46305  
iopath                    0.1.10                   pypi_0    pypi
jpeg                      9e                   h5eee18b_1  
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.7.2                    pypi_0    pypi
kornia-rs                 0.1.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      3.0                  h295c915_0  
libdeflate                1.17                 h5eee18b_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libiconv                  1.16                 h7f8727e_2  
libidn2                   2.3.4                h5eee18b_0  
libpng                    1.6.39               h5eee18b_0  
libstdcxx-ng              11.2.0               h1234567_1  
libtasn1                  4.19.0               h5eee18b_0  
libtiff                   4.5.1                h6a678d5_0  
libunistring              0.9.10               h27cfd23_0  
libwebp                   1.3.2                h11a3e52_0  
libwebp-base              1.3.2                h5eee18b_0  
lz4-c                     1.9.4                h6a678d5_0  
matplotlib                3.7.5                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46343  
mkl-service               2.4.0            py38h5eee18b_1  
mkl_fft                   1.3.8            py38h5eee18b_0  
mkl_random                1.2.4            py38hdb19cb5_0  
ncurses                   6.4                  h6a678d5_0  
nettle                    3.7.3                hbbd107a_1  
numpy                     1.24.3           py38hf6e8229_1  
numpy-base                1.24.3           py38h060ed82_1  
opencv-python             4.8.1.78                 pypi_0    pypi
openh264                  2.1.1                h4ff587b_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   3.0.11               h7f8727e_2  
packaging                 23.2                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
pillow                    10.0.1           py38ha6cbd5a_0  
pip                       23.3             py38h06a4308_0  
portalocker               2.8.2                    pypi_0    pypi
ptflops                   0.7.3                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.2.0           py38h06a4308_0  
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.18               h955ad1f_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch                   1.12.1          py3.8_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0           py38h06a4308_0  
safetensors               0.4.0                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                68.0.0           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0  
termcolor                 2.3.0                    pypi_0    pypi
thop                      0.1.1-2209072238          pypi_0    pypi
timm                      0.6.13                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torchaudio                0.12.1               py38_cu113    pytorch
torchinfo                 1.8.0                    pypi_0    pypi
torchvision               0.13.1               py38_cu113    pytorch
tqdm                      4.66.1                   pypi_0    pypi
typing_extensions         4.7.1            py38h06a4308_0  
tzdata                    2024.1                   pypi_0    pypi
urllib3                   1.26.16          py38h06a4308_0  
wheel                     0.41.2           py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
yacs                      0.1.8                    pypi_0    pypi
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  
zstd                      1.5.5                hc292b87_0